version: '3'
services: 
    core_api:
        build: 
            context: ./codigo
            dockerfile: Dockerfile
        container_name: "core-api-container"
        ports: 
            - "80:80"
        